version: "3"
services:
  lcmall:
    build:
      context: lcmall
      dockerfile: Dockerfile
    container_name: lcmall
    ports:
      - "9080:9080"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./lcmall/conf.d/application.yml:/application.yml
      - ./lcmall/conf.d/:/conf
      - ./lcmall/logs:/logs
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - mysql57
      - redis
    restart: always
  admin:
    image: nginx:1.21.3
    container_name: admin
    ports:
      - "8080:80"
    volumes:
      - ./admin/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./admin/logs:/var/log/nginx
      - ./admin/html/dist:/data/html
    restart: always
  evertabs:
    image: nginx:1.21.3
    container_name: evertabs
    ports:
      - "8081:80"
    volumes:
      - ./evertabs/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./evertabs/logs:/var/log/nginx
      - ./evertabs/html/dist:/data/html
    restart: always
